/// Data models for AI-generated resale listings.
///
/// Story 7.3: AI Resale Listing Generation (FR-RSL-02, FR-RSL-03)

/// A single resale listing generated by AI.
class ResaleListing {
  const ResaleListing({
    required this.id,
    required this.title,
    required this.description,
    required this.conditionEstimate,
    required this.hashtags,
    required this.platform,
    required this.generatedAt,
  });

  factory ResaleListing.fromJson(Map<String, dynamic> json) {
    return ResaleListing(
      id: json["id"] as String? ?? "",
      title: json["title"] as String? ?? "",
      description: json["description"] as String? ?? "",
      conditionEstimate: json["conditionEstimate"] as String? ?? "Good",
      hashtags: (json["hashtags"] as List<dynamic>?)
              ?.map((e) => e as String)
              .toList() ??
          [],
      platform: json["platform"] as String? ?? "general",
      generatedAt: json["generatedAt"] as String? ?? "",
    );
  }

  final String id;
  final String title;
  final String description;
  final String conditionEstimate;
  final List<String> hashtags;
  final String platform;
  final String generatedAt;

  Map<String, dynamic> toJson() {
    return {
      "id": id,
      "title": title,
      "description": description,
      "conditionEstimate": conditionEstimate,
      "hashtags": hashtags,
      "platform": platform,
      "generatedAt": generatedAt,
    };
  }
}

/// Item metadata returned alongside the listing.
class ResaleListingItem {
  const ResaleListingItem({
    required this.id,
    this.name,
    this.category,
    this.brand,
    this.photoUrl,
  });

  factory ResaleListingItem.fromJson(Map<String, dynamic> json) {
    return ResaleListingItem(
      id: json["id"] as String? ?? "",
      name: json["name"] as String?,
      category: json["category"] as String?,
      brand: json["brand"] as String?,
      photoUrl: json["photoUrl"] as String? ?? json["photo_url"] as String?,
    );
  }

  final String id;
  final String? name;
  final String? category;
  final String? brand;
  final String? photoUrl;
}

/// The full result of a resale listing generation request.
class ResaleListingResult {
  const ResaleListingResult({
    required this.listing,
    required this.item,
    required this.generatedAt,
  });

  factory ResaleListingResult.fromJson(Map<String, dynamic> json) {
    final listingJson = json["listing"] as Map<String, dynamic>? ?? {};
    final itemJson = json["item"] as Map<String, dynamic>? ?? {};

    // The generatedAt may be at the top level or inside listing
    final generatedAt = json["generatedAt"] as String? ?? "";

    // Inject generatedAt into listing json if not present
    if (!listingJson.containsKey("generatedAt")) {
      listingJson["generatedAt"] = generatedAt;
    }

    return ResaleListingResult(
      listing: ResaleListing.fromJson(listingJson),
      item: ResaleListingItem.fromJson(itemJson),
      generatedAt: generatedAt,
    );
  }

  final ResaleListing listing;
  final ResaleListingItem item;
  final String generatedAt;
}
